package fantix:examples;

interface stdio {
  /// Print a line of text to standard output
  println: func(line: string);
}

world basic {
  import stdio;

  /// Say hello to a specified person
  export hello: func(name: string);
}
