[package]
name = "wit-bindgen-mbt"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, optional = true }
heck = { workspace = true }
wit-bindgen-core = { workspace = true }
